### ISSUE TITLE
Not possible to remove password

### ISSUE THREAD

**Issue by alexsahka** [ex0nuss/Remote-Wake-Sleep-On-LAN-Docker#5]
If PASSPHRASE is removed, after deploying the container it returns back with the "admin" password.

If PASSPHRASE is empty, after deploying the container it returns back with the "admin" password.
 
![image](https://user-images.githubusercontent.com/7469537/169768273-6228e1f8-edc4-44ff-9772-c79f83c6e5f6.png)

Thank you.

**Comment by SmartPhoneLover** [comment]
I can confirm the same thing. +1

**Comment by ex0nuss** [comment]
@SmartPhoneLover Correct!

- If no PASSPHRASE is specified the default is used which is `admin`. This is for security reasons, so the default setups always uses a passphrase ;)
- If you don't want a passphrase, you need to set an empty env-var like this:
```
    environment:
      - PASSPHRASE=
      - APACHE2_PORT=8001
      - RWSOLS_COMPUTER_NAME="...","..."
      - RWSOLS_COMPUTER_MAC="...","..."
      - RWSOLS_COMPUTER_IP="...","..."
```

Unfortunately is not possible for me to remove the "Enter Passphrase" input field because I didn't develop the software. Just leave the field empty and hit "Wake Up!"
